### ISSUE TITLE
Pascal Case the default global variables

### ISSUE THREAD

**Issue by unional** [KoryNunn/globalify#10]
Can use `pascal-case` for that. Just need to strip the first '@' for scoped package.

```js
pascalCase('crel') // Crel
pascalCase('some-module-with-dash') // SomeModuleWithDash
pascalCase('unional/logging') // UnionalLogging
```

**Comment by KoryNunn** [comment]
This is more preference based, and it is pretty trivial to pass a custom global name, so I'm not going to implement it unless there is a pragmatic reason.

**Comment by unional** [comment]
Because by default `some-module` will fail, the global variable created doesn't make sense. Same for scoped package.

**Comment by KoryNunn** [comment]
ah, good point. I'm not sold on pascal case, because that usually implys a constructor, but i recon camel case is a good default, given the ease of overriding.

**Comment by unional** [comment]
I don't know. Namespaces are typically Pascal case, even in JavaScript. Albeit on the first one.

The most know namespace frenzy that I know of: `ExtJS`
`Ext.action`
`Ext.direct`

`react` also place itself as `React` globally.

**Comment by KoryNunn** [comment]
I'm going off JS language standards, not library/framework convention.

With #6, it might be best to be able to pass a custom global namer function that can do whatever transformation people want, considering it would involve potentially many globalified deps.

**Comment by ShawnTalbert** [comment]
I'd suggest that a very strong 'JS language standards' example is the `Math` global object.

**Comment by KoryNunn** [comment]
@ShawnTalbert Most information on the Math object explicitly state that it cannot be instantiated because almost every other pascal case global is a constructor function. The fact that Math is pascal case is a quirk, not an example to be followed.
